plugins {
    id 'com.android.application'
}

android {
    namespace 'com.stnk.rootassistant'
    compileSdk 34

    defaultConfig {
        applicationId "com.stnk.rootassistant"
        minSdk 26
        targetSdk 34
        versionCode 7002
        versionName "7.2"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
